---
# Copy Ceph configs to host
- include: copy_configs.yml

# let the first ganesha create configs and users
- include: create_configs.yml
  when:
    inventory_hostname == groups[nfs_group_name][0] and
    not mon_containerized_default_ceph_conf_with_kv

# Copy Ganesha configs to host
- include: fetch_configs.yml
  when: not mon_containerized_deployment_with_kv

- include: selinux.yml
  when: ansible_os_family == 'RedHat'

- include: start_docker_nfs.yml

